### ISSUE TITLE
colab notebook request

### ISSUE THREAD

**Issue by GeorvityLabs** [jmliu88/HeSer#2]
hope you guys make a colab notebook for this!
would be great to have a test

**Comment by demirklvc** [comment]
yes!!! :) we need a colab please

**Comment by ramnnv** [comment]
You have time to buy a graphics card and learn how to use python until this release.

**Comment by loboere** [comment]
maybe my great grandkids will get to see this release

**Comment by 850552586** [comment]
when can i see your great amazing work?maybe 2000 years later
